### ISSUE TITLE
Port the extension to GNOME 44

### ISSUE THREAD

**Issue by jeffshee** [jeffshee/gnome-ext-hanabi#52]
Tested with Fedora 38 Beta

### Issues
- [x] `JS ERROR: TypeError: Meta.later_add is not a function`
- [x] Renderer not launching on Wayland
- [ ] Top panel isn't visible after login to the Shell
`panelBox` is not mapped for some reason. Switching workspace can "fix" the issue. Also, it is fixable by calling `.show()` function in the `panelBox`.

**Comment by jeffshee** [comment]
Closed. The remaining issue is being tracked as a separate issue.
