### ISSUE TITLE
Add web renderer

### ISSUE THREAD

**Issue by jeffshee** [jeffshee/gnome-ext-hanabi#80]
**Description**
This is the meta thread for the progress of adding a web renderer to the Hanabi extension.

**Progress**
- [ ] Add preference options for the web renderer to the `prefs.js`
- [x] Integrate the build processes for `gstcefsrc` and `gtk4paintablesink` into meson
- [ ] Test `gstcefsrc` with `gtk4paintablesink` and `clappersink`

**Related works**
- #33
- #78

**Comment by jeffshee** [comment]
@Gouster4 

> Im really interested into website (homeassistant) as wallpaper for gnome on wayland.

Just for reference, what's your use case (expected result)? 
Do you expect to be able to interact (with mouse/keyboard) with the website that you set as wallpaper? If yes, why?

**Comment by ayasa520** [comment]
[gstcefsrc](https://github.com/centricular/gstcefsrc) does work. Compared with wpewebkit or webkitgtk, it has fewer rendering problems (such as strange flickering), but it‘s dependency is so heavy. 

https://github.com/user-attachments/assets/a765e778-2024-455c-86e0-118d05953712
